package sunseeker.telemetry.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.knowm.xchart.XChartPanel;
import sunseeker.telemetry.ui.table.SummaryTable;

import javax.swing.*;
import java.awt.*;

/**
 * Created by aleccarpenter on 6/11/17.
 */
public class LiveDataFrame extends JFrame {
    private JPanel mainPanel;
    private JPanel graphPanel;
    private JPanel configPanel;

    public LiveDataFrame(XChartPanel chartPanel, SummaryTable summaryTable) {
        super("Sunseeker Telemetry");

        setPreferredSize(new Dimension(960, 720));
        setResizable(false);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        JScrollPane scrollPane = new JScrollPane(summaryTable);
        scrollPane.setBorder(BorderFactory.createEmptyBorder()); // TODO: test for this
        scrollPane.setBorder(null);

        add(mainPanel);
        graphPanel.add(chartPanel);
        configPanel.add(scrollPane);

        pack();
    }

    public JPanel getGraphPanel() {
        return graphPanel;
    }

    public JPanel getConfigPanel() { return configPanel; }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(20, 20, 20, 20), -1, -1));
        mainPanel.setBackground(new Color(-4473925));
        graphPanel = new JPanel();
        graphPanel.setLayout(new BorderLayout(0, 0));
        graphPanel.setBackground(new Color(-4473925));
        mainPanel.add(graphPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(920, 360), null, 0, false));
        configPanel = new JPanel();
        configPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(configPanel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
